### PR TITLE
OpenGL related bindings

### PR DESCRIPTION
**Pull request by Oldes**

### CODE REVIEW

**Comment by dockimbel** [comment]
In case you missed it, there is already such binding: https://github.com/ldci/glfw-red

**Comment by Oldes** [comment]
You are right.. I missed it as it is not part of Red/Code... I will check
it too. Thanks. For the quick look my glfw3 binding is more complete as it
contains docs from the c header.

Btw.. I'm now working on opengl itself.. where funcions (from version >
1.1) must be loaded in runtime... I have already some working tests, but
wonder if I could use dynamic loading as is mentioned in your Trello task.
If for nothing else.. at least to share the data structure.

**Comment by Oldes** [comment]
The thing is, that now I must do code like this:
```
#define glGenVertexArraysProc! [ function! [n [integer!] arrays [int-ptr!]] ]
glGenVertexArrays: as glGenVertexArraysProc! glfwGetProcAddress "glGenVertexArrays"
```
But OpenGL contains hundreds of functions and it would be wasting to load all of them. On the other side, it would be tiresome to define the one which are needed manually like in example above.

I already have the function definitions and can produce any format needed for Red/System compiler. I also volunteer to write the compiler code, just would like to know @dockimbel 's design notes on that field.

**Comment by Oldes** [comment]
Using define for all functions is quite slow... it takes 19s to compile source which includes all GL definitions... so it would be better to avoid it. @dockimbel  Could I implement another `#import` version which would for above code look like:

```
#import [
	glfwGetProcAddress stdcall [
		glGenVertexArrays: "glGenVertexArrays" [n [integer!] arrays [int-ptr!]]
	]
]
```
So instead there would be just one change, where the DLL file name is replaced with loading function?

**Comment by qtxie** [comment]
You can use `alias`.
```
glGenVertexArraysProc!: alias function! [n [integer!] arrays [int-ptr!]] ]
glGenVertexArrays: as glGenVertexArraysProc! glfwGetProcAddress "glGenVertexArrays"
```

**Comment by Oldes** [comment]
@qtxie thanks for respond, but using alias is not that much speed gain... it is 14s instead of 19s... but for sure it helps to catch errors as it does more checks than simple define.

But the slower compilation is there, because the full GL binding with extensions is really huge.. it is 1MB in 2 files not counting the already pushed `glfw3.reds` It contains 5478 defines, 2596 function aliases and 335 classic library imports.

 Anyway.. problem is not with speed, but how user could use it, because one have to load functions defined as aliases before using them in real code, which is doable, but not much friendly... that is why I propose the import definition, where you would provide loading function instead of name of the dynamic library. Unfortunately... as I made some experiments if I could do such a import myself, I noticed that there are places where I hit with my limited knowledge... I can count the functions usage, but I'm not sure how/when/where correctly generate the loading function call to obtain the function pointer which is used with classic import.

**Comment by Oldes** [comment]
Maybe it is good idea to split the extensions file into multiple files per vendors.

**Pull request merged**
