### PR TITLE
FEAT: load-library - Red/System crossplatform function for procedures dynamic loading

### PR DESCRIPTION
**Pull request by Oldes**

### CODE REVIEW

**Comment by Oldes** [comment]
@dockimbel I have a question... as is in the `usage` example this code works:
```
my-lib: load-library "Kernel32.dll"
FreeLibraryProc!: alias function! [hmod [pointer! [integer!]] return: [integer!]] 
my-free-library: as FreeLibraryProc! load-procedure my-lib "FreeLibrary"
print-line my-free-library my-lib
```
But I cannot figure out, how to conditionally load the function.. for example this is not working:
```
my-lib: load-library "Kernel32.dll"
FreeLibraryProc!: alias function! [hmod [pointer! [integer!]] return: [integer!]] 
my-free-library: declare FreeLibraryProc!
if my-lib <> null [ ;test if the library was really loaded
	my-free-library: as FreeLibraryProc! load-procedure my-lib "FreeLibrary"
]
print-line my-free-library my-lib
```

Any advice?

**Comment by dockimbel** [comment]
What do you mean by "not working"?

**Comment by Oldes** [comment]
Above code does not compile. It throws error:
```
*** Compilation Error: undefined symbol: my-free-library 
```
on line with `print-line my-free-library my-lib`

**Comment by Oldes** [comment]
Without `my-free-library: declare FreeLibraryProc!` it chocke with:
```
*** Compilation Error: variable not declared 
```
on line inside the condition

**Comment by Oldes** [comment]
So I can say... it works only when defined in root of the code.

**Comment by Oldes** [comment]
In above commit I do the loading with check inside wrapper function which is more safe, but still wonder if original version could work somehow too.

**Pull request closed without merging**
