### PR TITLE
Update spiral.red

### PR DESCRIPTION
**Pull request by DideC**
Now use timer instead of mouse mouvments.
Also simplified and cleaned the code a bit.

### CODE REVIEW

**Comment by dockimbel** [comment]
@DideC I think you missed the `v0.6.1` branch: https://github.com/red/code/tree/v0.6.1

Please propose a new PR against that branch (timer has already been integrated in the spiral.red script, but you can apply your other changes).

**Comment by DideC** [comment]
Accessing your link give me a 404.
And in the browser, Github Red\code, "Code" tab, the "Branch" selector show me only a "Master" branch, the "Tags" tab show only "v0.6.0".

**Comment by dockimbel** [comment]
@DideC You're still lagging behind, the 0.6.1 branch has been merged into master a few hours ago. ;-)

**Comment by ghost** [comment]
@dockimbel Merged into master? The master branch shows last commit 3 months ago. And according to your activity feed, you deleted 0.6.1 branch without merging it into master.

**Comment by dockimbel** [comment]
Indeed, I forgot to push the merge online. It's done now.

**Comment by DideC** [comment]
Github say there is a "conflict that must be resolved" But I can't see what is the problem.
Do you know what it means ?

**Comment by dockimbel** [comment]
Did you pull the latest version from red/code before making the PR? If not, you need to close the PR, pull, resolve the conflicts, then open a new PR.

**Comment by DideC** [comment]
I close this PR and will redone it.

**Pull request closed without merging**
