### PR TITLE
JSON support.

### PR DESCRIPTION
**Pull request by rebolek**

### CODE REVIEW

**Comment by dockimbel** [comment]
```
>> json/decode {{"key": null}}
== #(
)
```
Is it the desired behavior?

**Comment by rebolek** [comment]
Can we get fully compatible JSON loader/saver in Red? IMO no, we do not have datatype that is fully compatible with JS' object - `map!` cannot store `none` and `object!` cannot store keys that are not `word!`s.

Is this good enough loader/saver? I think that it is good enough compromise. It is probably a question of preferences.

**Comment by dockimbel** [comment]
> we do not have datatype that is fully compatible with JS' object

`hash!` should work fine for loading JS objects, though, its API is not enforcing a key/value model with no duplicates, so it would require extra effort from users when building one fully compatible with JSON (though the JSON encoder could just error out on duplicate keys).

Partial JSON support is not "JSON support". It's probably good enough for a personal project, but a JSON *library* cannot decently only partially support it (and that's not a matter of preferences, but matter of not deceiving the users).

**Comment by rebolek** [comment]
Hm. What about having two modes (for decoder), strict that will return `hash!` and relaxed, that will return `map!` which would be fine in most cases?

**Comment by dockimbel** [comment]
We need a working solution out of the box, the user should not have to think if its JSON input has null values or not.

**Comment by rebolek** [comment]
Ok, so you prefer it to return `hash!` and conversion to `map!` should be done by user manually, if I understand it?

**Comment by dockimbel** [comment]
No, JSON being such a big standard, needs a great support in Red. It is not something that should be rushed, but designed properly, which means, first solving the different problems, finding the best possible solutions.

**Comment by rebolek** [comment]
OK, I will delete the pull request then.

**Comment by xaduha** [comment]
@rebolek @dockimbel 

Hi, I noticed there's https://github.com/red/wallet/blob/master/libs/JSON.red now, should it be here too? Or is it going to be a part of main repo?

**Pull request closed without merging**
